auction/auth.py
from flask import Blueprint, session, redirect, url_for, render_template, flash
from auction.forms import LoginForm, RegisterForm
from werkzeug.security import generate_password_hash,check_password_hash
from .models import User
from flask_login import login_user, login_required, logout_user
from . import db


authenticationbp = Blueprint('authentication', __name__, url_prefix='/authentication')

@authenticationbp.route('/login', methods=['GET', 'POST'])
def login():
    login_form_instance = LoginForm()
    error = None

    if (login_form_instance.validate_on_submit()==True):
        #Retrieve submitted username and password from the database
        user_name = login_form_instance.user_name.data
        password = login_form_instance.password.data
        u1 = User.query.filter_by(name=user_name).first()

        #If user is not found within the database
        if u1 is None:
            error = 'Incorrect Username or Password'
        #Check the password
        elif not check_password_hash(u1.password_hash, password): 
            error = 'Incorrect Username or Password'
        if error is None:
            login_user(u1)
            return redirect(url_for('main.index'))
        else:
            flash(error, 'danger')
    return render_template('authentication/login.html', form=login_form_instance, heading = 'Login')


@authenticationbp.route('/register', methods=['GET', 'POST'])
def register():
    register_form_instance = RegisterForm()

    if (register_form_instance.validate_on_submit() == True):
        #Retrieve information from the Form
        uname = register_form_instance.user_name.data
        pwd = register_form_instance.password.data
        email = register_form_instance.email.data
        contact = register_form_instance.contact_num.data
        address = register_form_instance.address.data

        #Check if the user exists
        u1 = User.query.filter_by(name=uname).first()
        if u1:
            flash('This userame already exists, please attempt login!', 'danger')
            return redirect(url_for('authentication.login'))

        pwd_hash = generate_password_hash(pwd)
        #Create a new user
        new_user = User(name=uname, password_hash=pwd_hash, email_id=email, contact_num=contact, address=address)
        db.session.add(new_user)
        db.session.commit()
        
        flash('Account successfully created! Please login.', 'success')
        return redirect(url_for('authentication.login'))
    else:
        return render_template('authentication/register.html', form=register_form_instance, heading = 'Register')


@authenticationbp.route('/logout')
@login_required
def logout():
    logout_user()
    flash("You have successfully logged out!", 'success')
    return redirect(url_for('authentication.login'))

auction/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash 
from .models import Listing
from sqlalchemy import or_

# Create main blueprint
mainbp = Blueprint('main', __name__)

@mainbp.route('/')
def index():
    listings = Listing.query.filter_by(status='Active').all()
    return render_template('index.html', listings=listings)

@mainbp.route('/search')
def search():
    #get the search string from request
    if request.args['search']:
        item = "%" + request.args['search'] + '%'
    #use filter and like function to search for matching item
        listing = Listing.query.filter(
            or_(
                Listing.title.like(item),
                Listing.cpu.like(item),
                Listing.brand.like(item),
                Listing.ram_gb.like(item),
                Listing.storage_gb.like(item)
            ), Listing.status=='Active'
        )
        # Search result message 
        resultMessage = "{0} results matching '{1}'".format(listing.count(), request.args['search'])
        flash (resultMessage)
        return render_template('index.html', listings=listing)
    else:
        return redirect(url_for('main.index'))

auction/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />

    <!-- External CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css')}}"
    />

    <!-- Icons -->
    <script
      src="https://kit.fontawesome.com/48067674f6.js"
      crossorigin="anonymous"
    ></script>

    <title>Browse | techprowl</title>
  </head>

  <body>
    <header style="margin-top: 100px">
      <!-- Navbar -->

      <nav
        class="navbar navbar-expand-lg navbar-dark fixed-top blue-background"
      >
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="{{url_for('main.index')}}"
              ><img
                src="{{ url_for('static', filename='img/logo.png')}}"
                alt="logo"
                width="180px"
            /></a>
          </div>

          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarResponsive"
            aria-controls="navbarResponsive"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">
              <li class="nav-item active mr-lg-4 nav-item-collapse">
                <a
                  class="navbar-link text-white"
                  href="{{url_for('main.index')}}"
                  >Browse</a
                >
              </li>
              <li class="nav-item mr-lg-4 nav-item-collapse">
                <a
                  class="navbar-link text-white"
                  href="{{url_for('listing.createlisting')}}"
                  >Sell</a
                >
              </li>
              <li class="nav-item mr-lg-4 nav-item-collapse">
                <a
                  class="navbar-link text-white"
                  href="{{url_for('listing.mylistings')}}"
                  >My Listings</a
                >
              </li>
              <li class="nav-item mr-lg-4 nav-item-collapse">
                <a
                  class="navbar-link text-white"
                  href="{{url_for('listing.watchlist')}}"
                  >Watch List</a
                >
              </li>
            </ul>

            <div class="ml-auto">
              <!-- Show message and 'logout' button if user is not already logged in-->
              {% if current_user.is_authenticated %}
              <p class="text-white mr-2 welcome-msg">
                Welcome, {{current_user.name}} 👋
              </p>
              <a
                href="{{url_for('authentication.logout')}}"
                class="btn btn-outline-light btn-sm-block btn-login"
                >Logout</a
              >
              <!-- Show 'login' and 'sign up' buttons if user is not already logged in-->
              {% else %}
              <a
                href="{{url_for('authentication.login')}}"
                class="btn btn-outline-light btn-sm-block btn-login"
                >Login</a
              >
              <a
                href="{{url_for('authentication.register')}}"
                class="btn btn-light btn-sm-block btn-sign-up"
                >Sign Up</a
              >
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

      {% block header %} {% endblock %}
    </header>

    {% block content %} {% endblock %}

    <!-- Footer -->
    <footer class="mt-4">
      <div class="blue-background text-center py-3 text-white">
        2021 techprowl &copy;
      </div>
    </footer>

    <!--Bootstrap Core Javascript-->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

auction/templates/createlisting.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <!-- External CSS -->
  <link rel="stylesheet" href="css/styles.css">

  <!-- Icons -->
  <script src="https://kit.fontawesome.com/48067674f6.js" crossorigin="anonymous"></script>

  <title>Create Listing | techprowl</title>
</head>

<body>
  <header>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top blue-background">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="index.html"><img src="img/logo_2.png" alt="logo" width="180px"></a>
        </div>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
          aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav">
            <li class="nav-item active mr-lg-4 nav-item-collapse">
              <a class="text-white navbar-link" href="index.html">Buy</a>
            </li>
            <li class="nav-item mr-lg-4 nav-item-collapse">
              <a class="navbar-link text-white" href="createlisting.html">Sell</a>
            </li>
            <li class="nav-item mr-lg-4 nav-item-collapse">
              <a class="navbar-link text-white" href="#">My Listings</a>
            </li>
            <li class="nav-item mr-lg-4 nav-item-collapse">
              <a class="navbar-link text-white" href="watchlist.html">Watch List</a>
            </li>
          </ul>

          <div class="ml-auto">
            <button type="button" class="btn btn-outline-light btn-sm-block btn-login"></span>Login</button>
            <button type="button" class="btn btn-light btn-sm-block btn-sign-up"></span>Sign Up</button>
          </div>
        </div>
      </div>
    </nav>
  </header>

  <main style="margin-top: 100px;">
    <div class="container jumbotron mt-4 pt-3 pb-3" style>
      <div class="row align-items-center">
        <div class="col-md-8 text-center text-md-left">
          <h1 class="responsive-heading">Create New Listing</h1>
          <p>List your computers with us for a faster sale, and a better offer!</p>
        </div>

        <div class="col-md-4">
          <img class="img-fluid" src="img/createlisting.svg">
        </div>
      </div>
    </div>

    <!-- First Row-->

    <form class="container">
      <div class="row">
        <div class="form-group col-md-6">
          <label for="title-input">Listing Title</label>
          <input class="form-control" id="title-input" type="text" placeholder="Title...">
        </div>

        <div class="form-group col-md-6">
          <label for="brand-input">Brand</label>
          <select class="form-control" id="brand-input">
            <option value="" selected disabled>Please select</option>
            <option value="">Apple</option>
            <option value="">Microsoft</option>
            <option value="">Dell</option>
            <option value="">HP</option>
            <option value="">Lenovo</option>
            <option value="">Acer</option>
            <option value="">Asus</option>
            <option value="">MSI</option>
          </select>
        </div>
      </div>

      <!-- Second Row-->

      <div class="row">
        <div class="form-group col-md-6">
          <label for="cpu-input">CPU</label>
          <select class="form-control" id="cpu-input">
            <option value="" selected disabled>Please select</option>
            <option value="">i3</option>
            <option value="">i5</option>
            <option value="">i7</option>
          </select>
        </div>

        <div class="form-group col-md-6">
          <label for="ram-input">RAM</label>
          <select class="form-control" id="ram-input">
            <option value="" selected disabled>Please select</option>
            <option value="">4GB</option>
            <option value="">8GB</option>
            <option value="">16GB</option>
            <option value="">32GB</option>
            <option value="">64GB</option>
          </select>
        </div>
      </div>

      <!-- Third Row-->

      <div class="row">
        <div class="form-group col-md-6">
          <label for="storage-input">Storage</label>
          <select class="form-control" id="storage-input">
            <option value="" selected disabled>Please select</option>
            <option value="">64GB</option>
            <option value="">128GB</option>
            <option value="">256GB</option>
            <option value="">512GB</option>
            <option value="">1TB</option>
            <option value="">2TB</option>
          </select>
        </div>

        <div class="form-group col-md-6">
          <label for="condition-input">Condition</label>
          <select class="form-control" id="condition-input">
            <option value="" selected disabled>Please select</option>
            <option value="">Excellent</option>
            <option value="">Good</option>
            <option value="">Minor defects</option>
            <option value="">New</option>
            <option value="">Used</option>
          </select>
        </div>
      </div>

      <div class="row">
        <div class="form-group col-md-6">
          <label for="end-date-input" z>Date</label>
          <input class="form-control" type="date" value="2011-08-19" id="end-date-input">
        </div>

        <div class="form-group col-md-6">
          <label for="image-input">Upload Image</label>
          <div class="input-group">
            <div class="custom-file">
              <input type="file" class="custom-file-input" id="image-input">
              <label class="custom-file-label form-control">Choose file</label>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="form-group col-md-12">
          <label for="description-input">Description</label>
          <textarea class="form-control" id="description-input" cols="30" rows="5"
            placeholder="Description of listing..."></textarea>
        </div>
      </div>

      <button type="submit" class="btn btn-blue btn-sm-block">Post Listing</button>
    </form>
  </main>

  <!-- Footer -->
  <footer class="mt-4">

    <div class="footer-links p-3 p-sm-5 p-md-5 p-lg-5">
      <div class="container text-center">
        <div class="row">
          <div class="col-4">
            <h5 class="footer-heading text-primary mb-4">Company Info</h5>
            <p><a href="#">About techprowl</a></p>
            <p><a href="#">Careers</a></p>
            <p><a href="#">Newsroom</a></p>
            <p><a href="#">Testimonials</a></p>
          </div>

          <div class="col-4">
            <h5 class="footer-heading text-primary mb-4">Contact Us</h5>
            <p><a href="#">Email</a></p>
            <p><a href="#">Facebook</a></p>
            <p><a href="#">+61 0423 3120</a></p>
            <p><a href="#">Brisbane, Australia</a></p>
          </div>

          <div class="col-4">
            <h5 class="footer-heading text-primary mb-4">Navigation</h5>
            <p><a href="index.html">Buy</a></p>
            <p><a href="createlisting.html">Sell</a></p>
            <p><a href="#">My Listings</a></p>
            <p><a href="watchlist.html">Watch List</a></p>
          </div>
        </div>
      </div>

      <!-- Social Media Icons -->
      <div class="row text-center pt-5">
        <div class="col-md-12">
          <div>
            <a href="#" class="fb-ic social-icon">
              <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x blue-text"></i>
            </a>

            <a href="#" class="ins-ic social-icon">
              <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x blue-text"></i>
            </a>

            <a href="#" class="li-ic social-icon">
              <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x blue-text"></i>
            </a>
          </div>
        </div>
      </div>
    </div>

    <div class="blue-background text-center py-3 text-white">
      2020 techprowl &copy;
    </div>
  </footer>

  <!--Bootstrap Core Javascript-->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
  </script>
</body>

</html>

auction/templates/index.html
{% extends 'base.html' %}

{% block header %}
<div class="container jumbotron mt-4" style>
  <div class="row align-items-center">
    <div class="col-md-7 text-center text-md-left">
      <h1>Auction your used computers</h1>
      <p>Techprowl hosts auctions for a range of different brands of computers, both desktops and laptops from all
        around Australia.</p>
      <a class="btn btn-blue btn-lg" href="{{url_for('listing.createlisting')}}" role="button">Create Listing</a>
    </div>

    <div class="col-md-5">
      <img class="img-fluid" src="{{url_for('static', filename='img/shopphoto.svg')}}">
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<main>
  <!-- Available Auctions -->
  <div class="container text-center">
    <h2 class="responsive-heading">🔥 Hot Auctions Right Now 🔥</h2>
  </div>

  <!--Search bar-->
  <div class="container text-center ">
    <div class="row justify-content-center mt-3 pb-4">
      <div class="col-10 col-lg-7 col-xl-6">
        <form class="form-inline d-flex flex-nowrap input-group" action="{{url_for('main.search')}}" >
            <input type="text" name="search" class="form-control flex-grow-1 my-1" placeholder="Search for computers" id="inlineFormCustomSelectPref">
            <div class="input-group-append">
              <button type="submit" class="flex-shrink-1 btn btn-primary my-1">Search</button>
            </div>
        </form>
      </div>
    </div> 
  </div>
  
  

  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  <!-- check if there are any messages -->
  <div class="container">
    <div class="row mt-3 mb-4">
      <div class="col-md-3">
        {% for category, message in messages %}
        <!--loop through the messages-->
        <div class="text-muted ">{{ message }}</div>
        <!--display as alert-->
        {% endfor %}
      </div>
    </div>
  </div>
  {% endif %}
  {% endwith %}

  <!-- First Row -->
  <section>
    <div class="container">
      <div class="row mb-4">
          {% for listing in listings %}
          <div class="col-md-6 col-lg-3">
            <div class="card shadow-sm border-light mb-4 listing-card">
              <a href="{{url_for('listing.showlisting', id=listing.id)}}" class="position-relative">
                <img src="{{ listing.image_url }}" class="card-img-top" alt="image"> </a>
              <div class="card-body">
                <a href="{{url_for('listing.showlisting', id=listing.id)}}">
                  <h5 class="font-weight-normal">{{ listing.title }}</h5>
                </a>

                <div class="d-block">
                  <span class="text-muted font-small d-block mb-2"><i
                      class="fas fa-sort-numeric-up-alt orange-icon"></i> Total Bids:
                    <strong>{{ listing.total_bids }}</strong></span>
                </div>

                <div class="d-block">
                  <span class="text-muted font-small d-block mb-2"><i class="fas fa-tags orange-icon"></i> Current Bid:
                    <strong>${{ listing.current_bid }}</strong></span>
                </div>

                <div class="d-block">
                  <span class="text-muted font-small d-block mb-2"><i class="fas fa-user orange-icon"></i> Seller:
                    <strong>{{ listing.seller }}</strong></span>
                </div>

                <form action="{{url_for('listing.add_watchlist', listing=listing.id)}}" method="POST">
                  <button class="btn btn-blue btn-block" href="" type="submit"><i class="fas fa-eye"></i> Watch List</button>
                </form>
              </div>
            </div>
          </div>
          {% endfor %}
      </div>
  </section>
</main>
{% endblock %}